### ISSUE TITLE
Update stiebel-isg from @1.4.0 to @1.4.1 not working

### ISSUE THREAD

**Issue by FraatRamski** [unltdnetworx/ioBroker.stiebel-isg#10]
$ ./iobroker upgrade stiebel-isg
Update stiebel-isg from @1.4.0 to @1.4.1
NPM version: 6.4.1
npm install iobroker.stiebel-isg@1.4.1 --production --save --prefix "/opt/iobroker" (System call)
npm
 WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.stiebel-isg
npm WARN
 pg-pool@2.0.6 requires a peer of pg@>5.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /opt/iobroker/node_modules/iobroker.stiebel-isgnpm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.stiebel-isg'
npm ERR!  { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.stiebel-isg'
npm 
ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.stiebel-isg\'',npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/iobroker/node_modules/iobroker.stiebel-isg' }

npm ERR! npm ERR!
 The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm
 ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator (though this is not recommended).

npm
 ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-03-15T13_23_11_249Z-debug.log

ERROR: host.stariobroker Cannot install iobroker.stiebel-isg@1.4.1: 243
ERROR: process exited with code 25

**Comment by unltdnetworx** [comment]
This is a problem of the new ioBroker installation/permissions, isn't it? Installing it by the Github-Cat should work although. Please try and give a feedback/close the issue if it isn't a adapter-Problem.
Thank you.
