### ISSUE TITLE
Value type not float

### ISSUE THREAD

**Issue by itstartedwithac64** [unltdnetworx/ioBroker.stiebel-isg#15]
It seems to me that unter "HEIZEN" all numerical values are of type string. Whereas unter "Info" it is correct.
This makes it difficult to store it in an influxDB which is very sensitive to it.
Can this be configured somewhere?
Please see screenshots below:
Log entry with errors
![err1](https://user-images.githubusercontent.com/56322933/66433944-c1567580-ea21-11e9-862c-7b56774a0cfd.jpg)

Values in "HEIZEN" have a decimal comma
![err2](https://user-images.githubusercontent.com/56322933/66433945-c1567580-ea21-11e9-81cc-116182b34103.jpg)

values in "Info" have a decimal point
![err3](https://user-images.githubusercontent.com/56322933/66433946-c1ef0c00-ea21-11e9-8044-cd2143cd513f.jpg)

**Comment by unltdnetworx** [comment]
Fixed in Version 1.4.9.
