### ISSUE TITLE
Status of ISG not only true if it is available. Pleas set it to false if you could find it 

### ISSUE THREAD

**Issue by MartinEhg** [unltdnetworx/ioBroker.stiebel-isg#19]
at the object tree at 
stiebel-isg.0   -   INFO   -   STATUS   -   BETRIEBSSTATUS
you can find the stati of the ISG. Is it possible to set the status to **false** if it is not set?
Actually you only set it to **true** if you find it in the page.
Maybe you could implement a  routine that check all states and if you could not find the state
set it to **false**.

**Comment by MartinEhg** [comment]
I try this ... it work but is is a terrible solution ...


`async function getIsgStatus(sidePath) {
    const $ = await getHTML(sidePath);
    
// ###MEB###>>>>#### My patch for Stati of ISG to set false state
    let bStatusHeizen    = false;
    let bStatusEvuSperre = false;
    let bStatusVerdichter = false;
    let bStatusSchaltprogramm = false;
    let bStatusService = false;
    let bStatusHeizkreispumpe = false;
    let bStatusWarmwasser = false;
	let bStatusAbtauenVerdampfer = false;
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
	
	
	
    if($) {  
        let submenu = $('#sub_nav')
            .children()
            .first()
            .text()
            .replace(/[\-\/]+/g,"_")
            .replace(/[ \.]+/g,"")
            .replace(/[\u00df]+/g,"SS");

        $('.info').each((i, el) => {                
            let group = $(el)
                .find(".round-top")    
                .text()
                .replace(/[ \-]+/g,"_")
                .replace(/[\.]+/g,"")
                .replace(/[\u00df]+/,"SS");
            
            group = submenu + "." + group
            
            
  
            
            $(el).find('tr').each(function() {
                let valueName = $(this)
                    .find(".key")
                    .text();
                
                let key = $(this)
                    .find(".key")
                    .text()
                    .replace(/[ \-]+/g,"_")
                    .replace(/[\.]+/g,"")
                    .replace(/[\u00df]+/,"SS");

// ###MEB###>>>>#### My patch for Stati of ISG to set false state
				if(group == "STATUS.BETRIEBSSTATUS"){

					if(key == 'HEIZEN') {  bStatusHeizen = true; } 
					if(key == 'EVU-SPERRE') {  bStatusEvuSperre = true; } 
					if(key == 'VERDICHTER') {  bStatusVerdichter = true; } 
					if(key == 'SCHALTPROGRAMM_AKTIV') {  bStatusSchaltprogramm = true; } 
					if(key == 'SERVICE') {  bStatusService = true; } 
					if(key == 'HEIZKREISPUMPE') {  bStatusHeizkreispumpe = true; } 
					if(key == 'WARMWASSERBEREITUNG') {  bStatusWarmwasser = true; } 
					if(key == 'ABTAUEN_VERDAMPFER') {  bStatusAbtauenVerdampfer = true; } 
   
   				}
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
 
                //<img src="./pics/tec-symbol_an-8e8e8e.png" height="15">                   
                let param = $(this)
                    .find(".value")
                    .html();
                
                let value;

                if(param !== null){
                    if (param.search('symbol_an') > -1){
                        value = true;
                    }
                }
                
                let valType = typeof value;
                let valThisType = "state"
                
                if(valType !== null) {
                    if(value === true || value === false) {
                        valThisType = "boolean";
                    } else {
                        valThisType = "state";
                    }
                }

                let valueRole;

                if(value === true){
                    //adapter.log.error (valueName + " : " + value + " (" + valThisType + ")");
                    updateState (translateName("info") + "." + group,key,translateName(valueName),valThisType,"","indicator.state",value);                	
                }
            }); 
            
// ###MEB###>>>>#### My patch for Stati of ISG to set false state
            if(group == "STATUS.BETRIEBSSTATUS"){
				
				adapter.log.info ('bStatusEvuSperre=' + bStatusEvuSperre);
				adapter.log.info ('bStatusHeizen=' + bStatusHeizen);
				adapter.log.info ('bStatusVerdichter=' + bStatusVerdichter);
				adapter.log.info ('bStatusSchaltprogramm=' + bStatusSchaltprogramm);
				adapter.log.info ('bStatusService=' + bStatusService);
				adapter.log.info ('bStatusHeizkreispumpe=' + bStatusHeizkreispumpe);
				adapter.log.info ('bStatusWarmwasser=' + bStatusWarmwasser);
				adapter.log.info ('bStatusAbtauenVerdampfer=' + bStatusAbtauenVerdampfer);
     			
     			if(!bStatusEvuSperre)         { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.EVU-SPERRE',false); }
     			if(!bStatusHeizen) 		      { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZEN',false); }
     			if(!bStatusVerdichter)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.VERDICHTER',false); }
     			if(!bStatusSchaltprogramm)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SCHALTPROGRAMM_AKTIV',false); }
     			if(!bStatusService)           { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SERVICE',false); }
     			if(!bStatusHeizkreispumpe)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZKREISPUMPE',false); }
     			if(!bStatusWarmwasser)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.WARMWASSERBEREITUNG',false); }
     			if(!bStatusAbtauenVerdampfer) { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.ABTAUEN_VERDAMPFER',false); }
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
          }            
        })
    }  
}
`

**Comment by MartinEhg** [comment]
`async function getIsgStatus(sidePath) {
    const $ = await getHTML(sidePath);
    
// ###MEB###>>>>#### My patch for Stati of ISG to set false state
    let bStatusHeizen    = false;
    let bStatusEvuSperre = false;
    let bStatusVerdichter = false;
    let bStatusSchaltprogramm = false;
    let bStatusService = false;
    let bStatusHeizkreispumpe = false;
    let bStatusWarmwasser = false;
	let bStatusAbtauenVerdampfer = false;
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
	
	
	
    if($) {  
        let submenu = $('#sub_nav')
            .children()
            .first()
            .text()
            .replace(/[\-\/]+/g,"_")
            .replace(/[ \.]+/g,"")
            .replace(/[\u00df]+/g,"SS");

        $('.info').each((i, el) => {                
            let group = $(el)
                .find(".round-top")    
                .text()
                .replace(/[ \-]+/g,"_")
                .replace(/[\.]+/g,"")
                .replace(/[\u00df]+/,"SS");
            
            group = submenu + "." + group
            
            
  
            
            $(el).find('tr').each(function() {
                let valueName = $(this)
                    .find(".key")
                    .text();
                
                let key = $(this)
                    .find(".key")
                    .text()
                    .replace(/[ \-]+/g,"_")
                    .replace(/[\.]+/g,"")
                    .replace(/[\u00df]+/,"SS");

// ###MEB###>>>>#### My patch for Stati of ISG to set false state
				if(group == "STATUS.BETRIEBSSTATUS"){

					if(key == 'HEIZEN') {  bStatusHeizen = true; } 
					if(key == 'EVU-SPERRE') {  bStatusEvuSperre = true; } 
					if(key == 'VERDICHTER') {  bStatusVerdichter = true; } 
					if(key == 'SCHALTPROGRAMM_AKTIV') {  bStatusSchaltprogramm = true; } 
					if(key == 'SERVICE') {  bStatusService = true; } 
					if(key == 'HEIZKREISPUMPE') {  bStatusHeizkreispumpe = true; } 
					if(key == 'WARMWASSERBEREITUNG') {  bStatusWarmwasser = true; } 
					if(key == 'ABTAUEN_VERDAMPFER') {  bStatusAbtauenVerdampfer = true; } 
   
   				}
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
 
                //<img src="./pics/tec-symbol_an-8e8e8e.png" height="15">                   
                let param = $(this)
                    .find(".value")
                    .html();
                
                let value;

                if(param !== null){
                    if (param.search('symbol_an') > -1){
                        value = true;
                    }
                }
                
                let valType = typeof value;
                let valThisType = "state"
                
                if(valType !== null) {
                    if(value === true || value === false) {
                        valThisType = "boolean";
                    } else {
                        valThisType = "state";
                    }
                }

                let valueRole;

                if(value === true){
                    //adapter.log.error (valueName + " : " + value + " (" + valThisType + ")");
                    updateState (translateName("info") + "." + group,key,translateName(valueName),valThisType,"","indicator.state",value);                	
                }
            }); 
            
// ###MEB###>>>>#### My patch for Stati of ISG to set false state
            if(group == "STATUS.BETRIEBSSTATUS"){
				
				adapter.log.info ('bStatusEvuSperre=' + bStatusEvuSperre);
				adapter.log.info ('bStatusHeizen=' + bStatusHeizen);
				adapter.log.info ('bStatusVerdichter=' + bStatusVerdichter);
				adapter.log.info ('bStatusSchaltprogramm=' + bStatusSchaltprogramm);
				adapter.log.info ('bStatusService=' + bStatusService);
				adapter.log.info ('bStatusHeizkreispumpe=' + bStatusHeizkreispumpe);
				adapter.log.info ('bStatusWarmwasser=' + bStatusWarmwasser);
				adapter.log.info ('bStatusAbtauenVerdampfer=' + bStatusAbtauenVerdampfer);
     			
     			if(!bStatusEvuSperre)         { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.EVU-SPERRE',false); }
     			if(!bStatusHeizen) 		      { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZEN',false); }
     			if(!bStatusVerdichter)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.VERDICHTER',false); }
     			if(!bStatusSchaltprogramm)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SCHALTPROGRAMM_AKTIV',false); }
     			if(!bStatusService)           { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SERVICE',false); }
     			if(!bStatusHeizkreispumpe)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZKREISPUMPE',false); }
     			if(!bStatusWarmwasser)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.WARMWASSERBEREITUNG',false); }
     			if(!bStatusAbtauenVerdampfer) { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.ABTAUEN_VERDAMPFER',false); }
// ###MEB###<<<<#### My patch for Stati of ISG to set false state
          }            
        })
    }  
}
`

**Comment by MartinEhg** [comment]
`
async function getIsgStatus(sidePath) {
    const $ = await getHTML(sidePath);
    
/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
    let bStatusHeizen    = false;
    let bStatusEvuSperre = false;
    let bStatusVerdichter = false;
    let bStatusSchaltprogramm = false;
    let bStatusService = false;
    let bStatusHeizkreispumpe = false;
    let bStatusWarmwasser = false;
	let bStatusAbtauenVerdampfer = false;
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
	
	
	
    if($) {  
        let submenu = $('#sub_nav')
            .children()
            .first()
            .text()
            .replace(/[\-\/]+/g,"_")
            .replace(/[ \.]+/g,"")
            .replace(/[\u00df]+/g,"SS");

        $('.info').each((i, el) => {                
            let group = $(el)
                .find(".round-top")    
                .text()
                .replace(/[ \-]+/g,"_")
                .replace(/[\.]+/g,"")
                .replace(/[\u00df]+/,"SS");
            
            group = submenu + "." + group
            
            
  
            
            $(el).find('tr').each(function() {
                let valueName = $(this)
                    .find(".key")
                    .text();
                
                let key = $(this)
                    .find(".key")
                    .text()
                    .replace(/[ \-]+/g,"_")
                    .replace(/[\.]+/g,"")
                    .replace(/[\u00df]+/,"SS");

/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
				if(group == "STATUS.BETRIEBSSTATUS"){

					if(key == 'HEIZEN') {  bStatusHeizen = true; } 
					if(key == 'EVU-SPERRE') {  bStatusEvuSperre = true; } 
					if(key == 'VERDICHTER') {  bStatusVerdichter = true; } 
					if(key == 'SCHALTPROGRAMM_AKTIV') {  bStatusSchaltprogramm = true; } 
					if(key == 'SERVICE') {  bStatusService = true; } 
					if(key == 'HEIZKREISPUMPE') {  bStatusHeizkreispumpe = true; } 
					if(key == 'WARMWASSERBEREITUNG') {  bStatusWarmwasser = true; } 
					if(key == 'ABTAUEN_VERDAMPFER') {  bStatusAbtauenVerdampfer = true; } 
   
   				}
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
 
                //<img src="./pics/tec-symbol_an-8e8e8e.png" height="15">                   
                let param = $(this)
                    .find(".value")
                    .html();
                
                let value;

                if(param !== null){
                    if (param.search('symbol_an') > -1){
                        value = true;
                    }
                }
                
                let valType = typeof value;
                let valThisType = "state"
                
                if(valType !== null) {
                    if(value === true || value === false) {
                        valThisType = "boolean";
                    } else {
                        valThisType = "state";
                    }
                }

                let valueRole;

                if(value === true){
                    //adapter.log.error (valueName + " : " + value + " (" + valThisType + ")");
                    updateState (translateName("info") + "." + group,key,translateName(valueName),valThisType,"","indicator.state",value);                	
                }
            }); 
            
/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
            if(group == "STATUS.BETRIEBSSTATUS"){
				
				adapter.log.info ('bStatusEvuSperre=' + bStatusEvuSperre);
				adapter.log.info ('bStatusHeizen=' + bStatusHeizen);
				adapter.log.info ('bStatusVerdichter=' + bStatusVerdichter);
				adapter.log.info ('bStatusSchaltprogramm=' + bStatusSchaltprogramm);
				adapter.log.info ('bStatusService=' + bStatusService);
				adapter.log.info ('bStatusHeizkreispumpe=' + bStatusHeizkreispumpe);
				adapter.log.info ('bStatusWarmwasser=' + bStatusWarmwasser);
				adapter.log.info ('bStatusAbtauenVerdampfer=' + bStatusAbtauenVerdampfer);
     			
     			if(!bStatusEvuSperre)         { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.EVU-SPERRE',false); }
     			if(!bStatusHeizen) 		      { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZEN',false); }
     			if(!bStatusVerdichter)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.VERDICHTER',false); }
     			if(!bStatusSchaltprogramm)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SCHALTPROGRAMM_AKTIV',false); }
     			if(!bStatusService)           { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SERVICE',false); }
     			if(!bStatusHeizkreispumpe)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZKREISPUMPE',false); }
     			if(!bStatusWarmwasser)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.WARMWASSERBEREITUNG',false); }
     			if(!bStatusAbtauenVerdampfer) { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.ABTAUEN_VERDAMPFER',false); }
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
          }            
        })
    }  
}

`

**Comment by MartinEhg** [comment]
```
async function getIsgStatus(sidePath) {
    const $ = await getHTML(sidePath);

    
/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
    let bStatusHeizen    = false;
    let bStatusEvuSperre = false;
    let bStatusVerdichter = false;
    let bStatusSchaltprogramm = false;
    let bStatusService = false;
    let bStatusHeizkreispumpe = false;
    let bStatusWarmwasser = false;
	let bStatusAbtauenVerdampfer = false;
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
	
	
	
    if($) {  
        let submenu = $('#sub_nav')
            .children()
            .first()
            .text()
            .replace(/[\-\/]+/g,"_")
            .replace(/[ \.]+/g,"")
            .replace(/[\u00df]+/g,"SS");

        $('.info').each((i, el) => {                
            let group = $(el)
                .find(".round-top")    
                .text()
                .replace(/[ \-]+/g,"_")
                .replace(/[\.]+/g,"")
                .replace(/[\u00df]+/,"SS");
            
            group = submenu + "." + group
            
            
  
            
            $(el).find('tr').each(function() {
                let valueName = $(this)
                    .find(".key")
                    .text();
                
                let key = $(this)
                    .find(".key")
                    .text()
                    .replace(/[ \-]+/g,"_")
                    .replace(/[\.]+/g,"")
                    .replace(/[\u00df]+/,"SS");

/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
				if(group == "STATUS.BETRIEBSSTATUS"){

					if(key == 'HEIZEN') {  bStatusHeizen = true; } 
					if(key == 'EVU-SPERRE') {  bStatusEvuSperre = true; } 
					if(key == 'VERDICHTER') {  bStatusVerdichter = true; } 
					if(key == 'SCHALTPROGRAMM_AKTIV') {  bStatusSchaltprogramm = true; } 
					if(key == 'SERVICE') {  bStatusService = true; } 
					if(key == 'HEIZKREISPUMPE') {  bStatusHeizkreispumpe = true; } 
					if(key == 'WARMWASSERBEREITUNG') {  bStatusWarmwasser = true; } 
					if(key == 'ABTAUEN_VERDAMPFER') {  bStatusAbtauenVerdampfer = true; } 
   
   				}
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
 
                //<img src="./pics/tec-symbol_an-8e8e8e.png" height="15">                   
                let param = $(this)
                    .find(".value")
                    .html();
                
                let value;

                if(param !== null){
                    if (param.search('symbol_an') > -1){
                        value = true;
                    }
                }
                
                let valType = typeof value;
                let valThisType = "state"
                
                if(valType !== null) {
                    if(value === true || value === false) {
                        valThisType = "boolean";
                    } else {
                        valThisType = "state";
                    }
                }

                let valueRole;

                if(value === true){
                    //adapter.log.error (valueName + " : " + value + " (" + valThisType + ")");
                    updateState (translateName("info") + "." + group,key,translateName(valueName),valThisType,"","indicator.state",value);                	
                }
            }); 
            
/* ###MEB###>>>>#### My patch for Stati of ISG to set false state   */
            if(group == "STATUS.BETRIEBSSTATUS"){
				
				adapter.log.info ('bStatusEvuSperre=' + bStatusEvuSperre);
				adapter.log.info ('bStatusHeizen=' + bStatusHeizen);
				adapter.log.info ('bStatusVerdichter=' + bStatusVerdichter);
				adapter.log.info ('bStatusSchaltprogramm=' + bStatusSchaltprogramm);
				adapter.log.info ('bStatusService=' + bStatusService);
				adapter.log.info ('bStatusHeizkreispumpe=' + bStatusHeizkreispumpe);
				adapter.log.info ('bStatusWarmwasser=' + bStatusWarmwasser);
				adapter.log.info ('bStatusAbtauenVerdampfer=' + bStatusAbtauenVerdampfer);
     			
     			if(!bStatusEvuSperre)         { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.EVU-SPERRE',false); }
     			if(!bStatusHeizen) 		      { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZEN',false); }
     			if(!bStatusVerdichter)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.VERDICHTER',false); }
     			if(!bStatusSchaltprogramm)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SCHALTPROGRAMM_AKTIV',false); }
     			if(!bStatusService)           { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.SERVICE',false); }
     			if(!bStatusHeizkreispumpe)    { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.HEIZKREISPUMPE',false); }
     			if(!bStatusWarmwasser)        { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.WARMWASSERBEREITUNG',false); }
     			if(!bStatusAbtauenVerdampfer) { adapter.setState('stiebel-isg.0.Info.STATUS.BETRIEBSSTATUS.ABTAUEN_VERDAMPFER',false); }
/* ###MEB###<<<<#### My patch for Stati of ISG to set false state   */
          }            
        })
    }  
}
```

**Comment by unltdnetworx** [comment]
Due to individual heatings it's not possible to hardcode this. But you can do this on your own. You can find an idea here: https://forum.iobroker.net/topic/26210/test-adapter-stiebel-isg-v1-4-x-github/140
