### ISSUE TITLE
Values are overwritten

### ISSUE THREAD

**Issue by MartinEhg** [unltdnetworx/ioBroker.stiebel-isg#20]
If I write the value of "LÜFTUNGSSTUFE (Tag)", sometimes the old values overwrite my value after some seconds. Could it be, that the pull request overwrite all set Data before the new Values send to ISG?

**Comment by unltdnetworx** [comment]
The values are written in intervalls. The problem is, that the ISG is a little bit slow and so may be the value is overwritten.
