### ISSUE TITLE
Fehlendes False

### ISSUE THREAD

**Issue by thgonline** [unltdnetworx/ioBroker.stiebel-isg#25]
Hallo,

alle Felder in den kein True steht haben keinen Inhalt, wie z.B. False. Damit sind die Felder nicht bzw. nur sehr schwer auswertbar.

Gibt es eine Lösung dafür?

Hello,

all fields that do not contain True have no content, such as False. This means that the fields cannot be evaluated or can only be evaluated with great difficulty.

Is there a solution for this?

**Comment by unltdnetworx** [comment]
Hallo,
das Thema wurde schon im Forum und im Issue #19 behandelt.

Die Lösung lautet leider, eigenes Skript. Das ISG blendet die Werte leider nur aus statt sie auf false zu setzen.
