### ISSUE TITLE
Errors in Log after Update 1.5.2: (19357) unhandled promise rejection: Invalid URI "http:///?s=4,3,4"

### ISSUE THREAD

**Issue by Aare07** [unltdnetworx/ioBroker.stiebel-isg#29]
Hallo Michael
Ich habe zwei Themen:
1. Haben die Objekte im Zweig "Einstellungen" bewusst keine sprechenden Namen, d.H. stiebel-isg.0.Einstellungen.HEIZEN.ELEKTRISCHE NACHERWAERMUNG.**val41**  anstelle  ... NACHERWAERMUNG.**BIVALENZTEMPERATUR_HZG** 
oder ist das Folgefehler aus Problem 2?

2. Das eigentliche Problem: 
Nach dem der Adapter klaglos seinen Dienst verrichtete, gibt es nach dem Update auf 1.5.2 nur Fehler im Log.
Kann ich etwas Unternehmen um das Problem einzugrenzen?
Auszug ioBroker Log:
`
stiebel-isg.0 | 2020-08-10 10:36:00.844 | info | (19357) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
stiebel-isg.0 | 2020-08-10 10:36:00.843 | info | (19357) terminating
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at main (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:718:18)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at Array.forEach (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:719:9
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:379:21)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at getHTML (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:185:12)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at new Promise (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:186:9
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at request (/opt/iobroker/node_modules/request/index.js:53:10)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at new Request (/opt/iobroker/node_modules/request/request.js:127:8)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | at Request.init (/opt/iobroker/node_modules/request/request.js:273:31)
stiebel-isg.0 | 2020-08-10 10:36:00.815 | error | (19357) Error: Invalid URI "http:///?s=4,3,4"
stiebel-isg.0 | 2020-08-10 10:36:00.814 | error | (19357) unhandled promise rejection: Invalid URI "http:///?s=4,3,4"
Unhandled | 2020-08-10 10:36:00.814 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at main (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:718:18)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at Array.forEach (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:719:9
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:379:21)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at getHTML (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:185:12)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at new Promise (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:186:9
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at request (/opt/iobroker/node_modules/request/index.js:53:10)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at new Request (/opt/iobroker/node_modules/request/request.js:127:8)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | at Request.init (/opt/iobroker/node_modules/request/request.js:273:31)
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | (19357) Error: Invalid URI "http:///?s=4,3,3"
stiebel-isg.0 | 2020-08-10 10:36:00.813 | error | (19357) unhandled promise rejection: Invalid URI "http:///?s=4,3,3"
Unhandled | 2020-08-10 10:36:00.813 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at main (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:718:18)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at Array.forEach (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:719:9
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:379:21)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at getHTML (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:185:12)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at new Promise (<anonymous>)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:186:9
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at request (/opt/iobroker/node_modules/request/index.js:53:10)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at new Request (/opt/iobroker/node_modules/request/request.js:127:8)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | at Request.init (/opt/iobroker/node_modules/request/request.js:273:31)
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | (19357) Error: Invalid URI "http:///?s=4,3,2"
stiebel-isg.0 | 2020-08-10 10:36:00.812 | error | (19357) unhandled promise rejection: Invalid URI "http:///?s=4,3,2"
`

Umgebung: Aktuelles Raspberry 4 mit aktuellem ioBroker und ISG Version vom 2019 (meines Wissens auch aktuell)

Besten Dank für den tollen Adapter und Danke für Dein Engagement.
Beste Grüsse
Aare

**Comment by unltdnetworx** [comment]
Hallo Aare,

zu 1:
Bewusst ist relativ. Das musste leider sein, da die Weboberfläche des ISG dynamisch ausgelesen wird und die Einstellungen im Gegensatz zu den Infopunkten mit valXXX-Werten bezeichnet werden und so auch zurück übermittelt werden müssen. Daher sind nur die sprechenden Namen der Datenpunkte entsprechend benannt.

zu 2:
Kann es sein, dass du die Instanz des Adapter nicht konfiguriert hast? Es muss eine IP-Adresse eingetragen sein. Falls es nur einmalig zu diesen Fehlermeldungen gekommen ist, liegt es daran, dass der Adapter sofort gestartet wurde ohne, dass eine IP eingetragen war. Nach dem Eintrag einer IP oder des Hostnamens und Neustart der Instanz sollte das Problem behoben sein.

Falls es weiterhin zu Problemen kommt, bitte nochmal melden. Ansonsten bitte den Issue schließen.

Danke.

**Comment by unltdnetworx** [comment]
Hallo Aare,

zu 1:
Bewusst ist relativ. Das musste leider sein, da die Weboberfläche des ISG dynamisch ausgelesen wird und die Einstellungen im Gegensatz zu den Infopunkten mit valXXX-Werten bezeichnet werden und so auch zurück übermittelt werden müssen. Daher sind nur die sprechenden Namen der Datenpunkte entsprechend benannt.

zu 2:
Kann es sein, dass du die Instanz des Adapter nicht konfiguriert hast? Es muss eine IP-Adresse eingetragen sein. Falls es nur einmalig zu diesen Fehlermeldungen gekommen ist, liegt es daran, dass der Adapter sofort gestartet wurde ohne, dass eine IP eingetragen war. Nach dem Eintrag einer IP oder des Hostnamens und Neustart der Instanz sollte das Problem behoben sein.

Falls es weiterhin zu Problemen kommt, bitte nochmal melden. Ansonsten bitte den Issue schließen.

Danke.

**Comment by unltdnetworx** [comment]
Hallo Aare,

zu 1:
Bewusst ist relativ. Das musste leider sein, da die Weboberfläche des ISG dynamisch ausgelesen wird und die Einstellungen im Gegensatz zu den Infopunkten mit valXXX-Werten bezeichnet werden und so auch zurück übermittelt werden müssen. Daher sind nur die sprechenden Namen der Datenpunkte entsprechend benannt.

zu 2:
Kann es sein, dass du die Instanz des Adapter nicht konfiguriert hast? Es muss eine IP-Adresse eingetragen sein. Falls es nur einmalig zu diesen Fehlermeldungen gekommen ist, liegt es daran, dass der Adapter sofort gestartet wurde ohne, dass eine IP eingetragen war. Nach dem Eintrag einer IP oder des Hostnamens und Neustart der Instanz sollte das Problem behoben sein.

Falls es weiterhin zu Problemen kommt, bitte nochmal melden. Ansonsten bitte den Issue schließen.

Danke.

**Comment by Aare07** [comment]
Danke für die schnelle Antwort.
Ja das war das Problem

Noch was: Eine Webseite mit FAQ oder ein etwas umfangreicheres Readme wäre Top.  z.B. auch was mit der "enable expert values" Checkbox freigeschaltet wird
