### ISSUE TITLE
Insert state Systemstatus "keine Fehler"

### ISSUE THREAD

**Issue by nheuk** [unltdnetworx/ioBroker.stiebel-isg#3]
it wil lbe usefull when you can send an message when this state is changing. After the xmas holidays i come back to my cold house, because of an "Niederdruck Fehler" :-(

**Comment by unltdnetworx** [comment]
Do you mean the values in "stiebel-isg.0/info/status"? This should be done with individual scripts on each ioBroker installation. For example with trigger "on change"?! Because of different heatings/values.

**Comment by nheuk** [comment]
ok, i will do this with an individual script ;-)
