### ISSUE TITLE
Einheit bei Wärmemenge Heizen Tag Fehlerhaft:   00KWh

### ISSUE THREAD

**Issue by Aare07** [unltdnetworx/ioBroker.stiebel-isg#31]
Zuerst eine Beobachtung. Seit ISG auf Version 12.0  (automatisch 1 Jahr Gratisvertrag)  reagiert diese nicht mehr so träge bei Abfragen.

Bereits früher und auch jetzt Adapter V 1.5.3 mit ISG Version 12.00 (Build 123 oder so) habe ich eine fehlerhafte Einheit  00KWh  bei der Wärmemenge Tag

stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.VD_HEIZEN_TAG     5.45  00KWh

Denke da sind Wert / Einheit irgendwie durcheinander gekommen

2. Noch eine Frage zum Adapter. 
In diesen Werten habe ich keine Daten:
stiebel-isg.0.Info.STATUSANLAGE.BETRIEBSSTATUS.HEIZEN
stiebel-isg.0.Info.STATUSANLAGE.BETRIEBSSTATUS.WARMWASSERBEREITUNG
stiebel-isg.0.Info.STATUSANLAGE.BETRIEBSSTATUS.HEIZKREIS_1_PUMPE

Werden diese nicht erhoben / geliefert nur je nach WP Typ oder braucht es da ein Update?
Eigentliches Ziel wäre herauszufinden warum die Pumpe läuft. Für Heizung oder Warmwasser.
Die Wärmemenge Heizen und Warmwasser werden leider erst geschrieben wenn die WP bereits wieder gestoppt hat
stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.VD_HEIZEN_TAG und stiebel-isg.0.Info.WAERMEPUMPE.WAERMEMENGE.VD_WARMWASSER_TAG

Danke !

**Comment by unltdnetworx** [comment]
Danke für den Hinweis auf die Version 12.

Zu Frage 1:
Bitte einmal den Eintrag komplett löschen. Er wird im nächsten Durchlauf oder bei Neustart des Adapters wieder angelegt. Da die Einheiten automatisch generiert werden, lag vermutlich irgendwann mal ein Problem beim Auslesen vor.

Zu Frage 2:
Das ist ein bekanntes Problem. Diese Werte werden leider nur auf true oder gar nicht gesetzt. Das liegt an der Weboberfläche. Die zeigt die Punkte leider nie auf falsch, sondern eben nur an oder gar nicht. Es gibt im ioBroke Forum schon Lösungsvorschläge.

Falls das geholfen hat, bitte den Issue schließen.

**Comment by Aare07** [comment]
Habe Datenpunkte gelöscht, auch ISG Reboot und neustart Adapter und ioBroker.
Musste warten bis WP endlich auch Warmwasser erzeugt hat.

1. Leider immer noch identisch, die falsche Einheit bleibt.  
Sowohl wenn Wert = 0 ist wie auch heute wo ich im Wert Warmwasser heute Werte > 0 habe
Wage Vermutung/Spekulation: Da Warmwasser nur sporadisch erzeugtcht wird, ist Wert beim Neustarten des Adapters NULL und Einheit gerät durcheinander
Dann später wenn Tageswerte Warmwasser vorhanden sind wird nur der Wert gechrieben und Einheibt bleibt falsch.   ??

2. Danke für den Hinweis.
Darf ich anregen den Hinweis in das Readme aufzunehmen?  Oder in ein Wiki Eintrag, allenfalls mit aktuellem Lösungsbeispiel?
Der Thread ist halt schon sehr lang und mit unterschiedlichen teils alten Lösungsansätzen unübersichtlich.
Dann würden Newbies wie ich nicht unnötig die Entwickler beschäftigen....    ....hätten einen einfacheren Einstieg.

**Comment by unltdnetworx** [comment]
Kannst du mir bitte mal HTML-Quellcode der Seite aus der Weboberfläche zur Verfügung stellen? Ich kann das Problem nämlich nicht reproduzieren und werde vermutlich nicht auf Version 12 updaten.

Die Werte sollten eigentlich immer erscheinen, auch wenn kein Warmwasser erzeugt wurde. Dann eben mit 0 kWh.

**Comment by Aare07** [comment]
Wie gewünscht, nur Heizung gelaufen
[STIEBEL ELTRON Reglersteuerung_Info-Waermepumpe.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5455382/STIEBEL.ELTRON.Reglersteuerung_Info-Waermepumpe.txt)

und von heute, weder Heizung noch WW gelaufen
[STIEBEL ELTRON Reglersteuerung_Info-Waermepumpe_20201029.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5455398/STIEBEL.ELTRON.Reglersteuerung_Info-Waermepumpe_20201029.txt)

**Comment by unltdnetworx** [comment]
Ich bräuchte bitte den tatsächlichen HTML-Quellcode der Seite. Der Adapter parst die Seite und würde diesen Code einmal bei mir testen. Falls sich der Seitenaufbau etwas geändert hat, müsste hier vllt. nachgebessert werden.

Könntest du evtl. auch einmal eine zweite Instanz machen und beobachten, ob dort die Werte vllt. richtig angelegt werden? Ein anderes Problem wurde mit dem Adapter wurde durch eine neue Instanz wohl behoben.

**Comment by Aare07** [comment]
Hier die Seite als HTML-Quelltext angezeigt, hoffe das passt besser.

[STIEBEL ELTRON Reglersteuerung_Info-Waermepumpe_20201030_html.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5461862/STIEBEL.ELTRON.Reglersteuerung_Info-Waermepumpe_20201030_html.txt)

Leider mit der zweiten Instanz auch nicht funktioniert
Wie gesagt. Die 00kWh Einheiten gibt es nur beim Starten des Adapters wenn Datenpunkte neu erstellt werden müssen wenn da noch kein Wert steht ( 0 ) 
Wenn die Einheit einmal korrekt eingelesen wurde (bei mir wenn ich die Datenpunkte lösche und den Adapter neu Starte wenn die beiden Werte nicht 0 sind)
Das JSON der Datenpunkte .../ Info / Wärmepumpe vom neu eingerichteten Adapter und unten zwei Beispiele der falschen unit
[stiebel-isg.1.Info.WAERMEPUMPE_json.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5461927/stiebel-isg.1.Info.WAERMEPUMPE_json.txt)

"stiebel-isg.1.Info.WAERMEPUMPE.LEISTUNGSAUFNAHME.VD_HEIZEN_SUMME": {
    "type": "state",
    "common": {
      "name": "VD HEIZEN SUMME",
      "type": "number",
      "read": true,
      "write": false,
      **"unit": "0MWh",**
      "role": "value"
    },
  ...
  "stiebel-isg.1.Info.WAERMEPUMPE.LEISTUNGSAUFNAHME.VD_WARMWASSER_TAG": {
    "type": "state",
    "common": {
      "name": "VD WARMWASSER TAG",
      "type": "number",
      "read": true,
      "write": false,
      **"unit": "00KWh",**
      "role": "value"
    },`

**Comment by unltdnetworx** [comment]
Wow, der Fehler liegt tatsächlich am Quellcode. Wert und Einheit werden einfach ohne Leerezeichen aneinander gereiht.

Bitte den Adapter einmal über die Github-Katze updaten und die Datenpunkte löschen. Danach sollte die Werte, diesmal ohne führende Nullstellen angelegt werden.

**Comment by Aare07** [comment]
Leider dasselbe Ergebnis, keine Verbesserung.   
Aber:
Ich bin nicht sicher ob das mit der Github-Katze funktioniert hat.
Es hat zwar ganz brav ab Git installiert, die Versionsnummer des Adapters ist jedoch nach wie vor 1.5.3
- Muss ich nur die Katze anwerfen oder danach auch  "upload Adapter"?
- Beim GIT Install einfach Stiebel plus Debug wählen und gut ist?   (Entschuldige ist mein erstes Mal Github Install)

Hier das resultierende JSON 
[stiebel-isg.1.Info.WAERMEPUMPE_json-20201101.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5470000/stiebel-isg.1.Info.WAERMEPUMPE_json-20201101.txt)

**Comment by unltdnetworx** [comment]
Das Update über die Katze reicht eigentlich aus. Die Version hat sich nicht erhöht, weil ich das erst nach erfolgreicher Behebung des Problems gemacht hätte.

Hast du alle Punkte vorher gelöscht? Du kannst auch den ganzen Baum löschen und bei nächsten Neustart wieder anlegen lassen.

**Comment by Aare07** [comment]
Ja Datenpunkte Baum ist komplett neu aufgebaut:
1 den Baum der Instanz 1 komplett gelöscht
2. Update über Github Katze mit Option "Debug"
3. Konfig und Start des Adapters
4. Warten bis alles aufgebaut ist
5 Resultat das json vom 1.11.   
Leider Fehler noch drin

**Comment by unltdnetworx** [comment]
Dann bitte einmal den ganzen Adapter deinstallieren und direkt über Github installieren.

**Comment by Aare07** [comment]
Nun so gemacht, adapter deinstalliert, alle Datenpunkte gelöscht, ab github installiert, gestartet. Leider kein Erfolg.

[stiebel-isg.0.Info.WAERMEPUMPE_json_20201103.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5478597/stiebel-isg.0.Info.WAERMEPUMPE_json_20201103.txt)

**Comment by unltdnetworx** [comment]
Bitte nochmal testen. Update und Löschen der Datenpunkte sollte reichen.

**Comment by Aare07** [comment]
Funktioniert nun Super!
DANKE für Deine Arbeit am tollen Adapter und der Korrektur!
[stiebel-isg.0.Info.WAERMEPUMPE_20201105_json.txt](https://github.com/unltdnetworx/ioBroker.stiebel-isg/files/5490994/stiebel-isg.0.Info.WAERMEPUMPE_20201105_json.txt)
