### ISSUE TITLE
unhandled promise rejection: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by radebold** [unltdnetworx/ioBroker.stiebel-isg#36]
Hi since update to 1.6. i have an issue, so I goes back to 1.5.3 and all is working fine

![image](https://user-images.githubusercontent.com/25064101/104212829-ebbd8c80-5435-11eb-8f23-a8e69bd1a5eb.png)

stiebel-isg.0 | 2021-01-11 17:46:30.118 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
stiebel-isg.0 | 2021-01-11 17:46:30.118 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8147:76
stiebel-isg.0 | 2021-01-11 17:46:30.118 | error | at Object.ready (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:67:59)
stiebel-isg.0 | 2021-01-11 17:46:30.118 | error | (25467) TypeError: Cannot read property 'split' of undefined
stiebel-isg.0 | 2021-01-11 17:46:30.115 | error | (25467) unhandled promise rejection: Cannot read property 'split' of undefined

**Comment by unltdnetworx** [comment]
Did you edit the fields on the expert tab of the adapter settings?
Maybe there is an error within these fields.

**Comment by radebold** [comment]
no, I only updated to 1.6 and change nothing else.

I have to do this ?

**Comment by unltdnetworx** [comment]
Normally you don't have to. It should work properly without reconfiguration. But you can shorten the lines for sites you don't need.

Please try to restart or even reinstall the adapter. The datapoints will be there afterwards, so don't worry.

**Comment by radebold** [comment]
ok after reupdate it looks better, thx. for support
