### ISSUE TITLE
Warnungen nach Update auf js-controller 3.3

### ISSUE THREAD

**Issue by thgonline** [unltdnetworx/ioBroker.stiebel-isg#39]
`

stiebel-isg.0 | 2021-04-30 17:35:40.202 | warn | (5989) State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""
-- | -- | -- | --
stiebel-isg.0 | 2021-04-30 17:35:40.201 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.DO.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.201 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.200 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.MI.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.200 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.199 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.DI.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.199 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.198 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.MO.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.198 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.197 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.SO.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.197 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.196 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.SA.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.195 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.156 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.FR.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.156 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.EV-ERHOEHUNG.LATEST_VALUE.EV-ERHOEHUNG_LINE" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.155 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.17:38.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.155 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.LATEST_VALUE.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.154 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.16:35.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.154 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.LATEST_VALUE.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.153 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.16:34.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.153 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.LATEST_VALUE.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.152 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.16:16.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"
stiebel-isg.0 | 2021-04-30 17:35:40.152 | warn | (5989) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.ENERGIEMANAGEMENT-STATUS.LATEST_VALUE.ENERGIEMANAGEMENT-STATUS_XY" has wrong type "string" but has to be "number"

`

**Comment by Schimi1983** [comment]
habe das gleiche...

**Comment by unltdnetworx** [comment]
Bitte mal per Github updaten. Sollte behoben sein.

**Comment by Schimi1983** [comment]
Danach bekomme ich:

`

host.smarthome | 2021-05-02 21:26:21.672 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
stiebel-isg.0 | 2021-05-02 21:26:21.108 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
stiebel-isg.0 | 2021-05-02 21:26:21.108 | info | terminating
stiebel-isg.0 | 2021-05-02 21:26:21.108 | info | cleaned everything up...
stiebel-isg.0 | 2021-05-02 21:26:21.106 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-05-02 21:26:21.106 | error | Error: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-05-02 21:26:21.105 | error | uncaught exception: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-05-02 21:26:21.081 | info | starting. Version 1.7.0 in /opt/iobroker/node_modules/iobroker.stiebel-isg, node: v12.22.1, js-controller: 3.3.5

`

**Comment by unltdnetworx** [comment]
Sind die Fehler-Meldungen ebenfalls weg?

**Comment by thgonline** [comment]
Nein mit 1.7.1 kommen folgende meldungen bei mir:

`

stiebel-isg.0 | 2021-05-03 10:50:38.102 | warn | (21940) State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""
-- | -- | -- | --
stiebel-isg.0 | 2021-05-03 10:50:23.525 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.LUEFTEN.FEUCHTESCHUTZ.val364" has value "1" greater than max ""
stiebel-isg.0 | 2021-05-03 10:50:20.455 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.LUEFTEN.PASSIVKUEHLUNG.val90" has value "4" greater than max ""
stiebel-isg.0 | 2021-05-03 10:50:12.131 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.KUEHLEN.KUEHLBETRIEB HK1.val189" has value "1" greater than max ""
stiebel-isg.0 | 2021-05-03 10:46:57.668 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.KUEHLEN.KUEHLBETRIEB HK1.val189" has value "1" greater than max ""
stiebel-isg.0 | 2021-05-03 10:46:39.913 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.LUEFTEN.FEUCHTESCHUTZ.val364" has value "1" greater than max ""
stiebel-isg.0 | 2021-05-03 10:46:36.917 | warn | (21940) State value to set for "stiebel-isg.0.Einstellungen.LUEFTEN.PASSIVKUEHLUNG.val90" has value "4" greater than max ""
stiebel-isg.0 | 2021-05-03 10:46:27.366 | warn | (21940) State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""

`

**Comment by unltdnetworx** [comment]
Bitte einmal alle Datenpunkte manuell löschen. Adapter stoppen, in den Objekten den gesamten Datenbaum löschen und Adapter neustarten. Dann sollten die Fehler weg sein.

**Comment by thgonline** [comment]
Wie meinst du das bitte?

Wo die DP löschen?

Im Objekt dann Einstellungen, Info und Start mit dem Papierkorb recht inkl aller Unterobjekte löschen?

**Comment by unltdnetworx** [comment]
In der Zeile für "stiebel-isg.0" ist ganz hinten ein Papierkorb. Dort werden alle Unterobjekte gelöscht, genau.

**Comment by thgonline** [comment]
Das war keine gute Idee mit dem Löschen. Sieht nun so aus:

![Bildschirmfoto 2021-05-03 um 11 37 53](https://user-images.githubusercontent.com/63864319/116861817-0a71aa00-ac04-11eb-8513-31adfdd49b16.png)

**Comment by unltdnetworx** [comment]
Das ist kein Problem, dauert etwas, während alle Punkte angelegt werden. Einfach etwas warten und/oder links oben auf den Objekte aktualisieren Button drücken.

**Comment by thgonline** [comment]
Ok sieht gut aus und es sind keine Auffälligkeiten mehr im Log zu sehen!

Danke
