### ISSUE TITLE
state unit " °C" not compatible with Iot/Cloud adapter

### ISSUE THREAD

**Issue by nheuk** [unltdnetworx/ioBroker.stiebel-isg#4]
The iot-Adapter cannot insert a state as smartdevice which uses the unit " °C". Please remove the unnecessary space character.

**Comment by unltdnetworx** [comment]
Okay, I'll take a look. The unit is out of the isg itself.

**Comment by unltdnetworx** [comment]
I checked it. There is no space in the unit. It is optical in the objects view. Please close the issue, if this is the problem.

**Comment by nheuk** [comment]
delete all states and restart the adapter with follwing result, there ist still a space in the unit :-(

`{
  "from": "system.adapter.stiebel-isg.0",
  "ts": 1546976019879,
  "common": {
    "name": "ISTTEMPERATUR",
    "type": "number",
    "unit": " °C",
    "role": "value.temperature",
    "read": true,
    "write": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "stiebel-isg.0.Info.ANLAGE.WARMWASSER.ISTTEMPERATUR",
  "type": "state"
}`

**Comment by unltdnetworx** [comment]
Bug fixed
