### ISSUE TITLE
1.7.0 funktioniert nicht mehr

### ISSUE THREAD

**Issue by thgonline** [unltdnetworx/ioBroker.stiebel-isg#40]
Adapter lässt sich nicht mehr starten

`

host.rpi4-iobroker | 2021-05-02 19:30:23.613 | warn | Do not restart adapter system.adapter.stiebel-isg.0 because restart loop detected
-- | -- | -- | --
host.rpi4-iobroker | 2021-05-02 19:30:23.613 | info | Restart adapter system.adapter.stiebel-isg.0 because enabled
host.rpi4-iobroker | 2021-05-02 19:30:23.612 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
stiebel-isg.0 | 2021-05-02 19:30:22.729 | warn | (13301) Terminated (UNCAUGHT_EXCEPTION): Without reason
stiebel-isg.0 | 2021-05-02 19:30:22.728 | info | (13301) terminating
stiebel-isg.0 | 2021-05-02 19:30:22.727 | info | (13301) cleaned everything up...
stiebel-isg.0 | 2021-05-02 19:30:22.723 | error | - /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-05-02 19:30:22.723 | error | Require stack:
stiebel-isg.0 | 2021-05-02 19:30:22.723 | error | (13301) Exception-Code: MODULE_NOT_FOUND: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at require (internal/modules/cjs/helpers.js:74:18)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at Module.require (internal/modules/cjs/loader.js:887:19)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at Function.Module._load (internal/modules/cjs/loader.js:667:27)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | - /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | Require stack:
stiebel-isg.0 | 2021-05-02 19:30:22.722 | error | (13301) Error: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'
stiebel-isg.0 | 2021-05-02 19:30:22.720 | error | - /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-05-02 19:30:22.720 | error | Require stack:
stiebel-isg.0 | 2021-05-02 19:30:22.720 | error | (13301) uncaught exception: Cannot find module '/opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json'

`

**Comment by unltdnetworx** [comment]
Bitte nochmal testen.

**Comment by thgonline** [comment]
Mit der 1.7.1 läuft es wieder
