### ISSUE TITLE
1.7.1 Fehler

### ISSUE THREAD

**Issue by Schimi1983** [unltdnetworx/ioBroker.stiebel-isg#42]
Hi,

nach dem Update auf 1.7.1 bekomme ich folgendes:

`

stiebel-isg.0 | 2021-05-03 10:59:49.403 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
stiebel-isg.0 | 2021-05-03 10:59:49.402 | info | terminating
stiebel-isg.0 | 2021-05-03 10:59:49.401 | info | cleaned everything up...
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.343 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.343 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.344 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.342 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.342 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.343 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.343 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.343 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.341 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.341 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.342 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.342 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.341 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.341 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.341 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.339 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.339 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.340 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.338 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.338 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.339 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.339 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.339 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.338 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.338 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.338 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.336 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.336 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.337 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.336 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.336 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.336 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.334 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.334 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.335 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.334 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.334 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.334 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.333 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:465:9 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.331 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.331 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "." at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23) at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3378:17) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:38 at Array.forEach (<anonymous>) at updateState (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:147:11) at /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:469:8 at Array.forEach (<anonymous>) at getIsgCommands (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:449:14) at processTicksAndRejections (internal/process/task_queues.js:97:5)
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | Error: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.332 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.331 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.331 | error | The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."
stiebel-isg.0 | 2021-05-03 10:59:49.331 | error | unhandled promise rejection: The id "Info.ANLAGE.STATISTIK." is invalid. Ids are not allowed to end in "."

`

**Comment by Schimi1983** [comment]
habe alle Objekte vorher gelöscht um "dienen sauberen" start zu haben

**Comment by unltdnetworx** [comment]
Bin auf der Suche nach der Ursache. Bei mir tritt das Problem nicht auf. Danke für die Rückmeldung.

**Comment by Schimi1983** [comment]
Mit den "offiziellen" Versionen kommen die Fehler nicht... (nur halt die Warnungen)....

**Comment by unltdnetworx** [comment]
Neuer Versuch

**Comment by Schimi1983** [comment]
Fehler ist weg... jetzt sieht es so aus (vorher wieder alles gelöscht gehabt)

![image](https://user-images.githubusercontent.com/4581474/116866737-3a24b000-ac0c-11eb-8f57-b2783bebb3bf.png)

**Comment by unltdnetworx** [comment]
Bitte einmal den Objekt-Baum aktualisieren. Der Aufbau aller Punkte dauert immer etwas, da diese dynamische generiert werden.

**Comment by Schimi1983** [comment]
habe ich... bliebt gleich... mir gehts um die Doppelten punkte... einmal richtig (mit unterpunkte) und einmal falsch geschrieben...

**Comment by unltdnetworx** [comment]
Das hatte ich auch erst. Aber mit dem Aktualisieren-Button ging es nach und nach weg. Komisch, ich hatte nicht mal das ursprüngliche Problem.

**Comment by Schimi1983** [comment]
ich warte mal 10min und versuche es dann nochmal mit aktualiesieren... habe gerade erst weidet die Objekte gelöscht... dauert noch bis er alles aufbaut....

Melde mich gleich

**Comment by unltdnetworx** [comment]
Das sollte eigentlich nicht nötig sein. Bei mir kam sowohl in der Testumgebung als auch im Livebetrieb das gleiche Problem, also mit abgeschnittenem letzten Buchstaben. Aber nach Klick auf "Seitenbaum neu aufbauen" waren alle falschen Punkte weg. Sieht nach Darstellungsfehler aus.

**Comment by unltdnetworx** [comment]
Kommando zurück, ich hatte einen Filter drin. Der Fehler ist auch bei mir.

**Comment by Schimi1983** [comment]
Du hast Recht.....

musste auf die "alte" Ansicht wechseln... da funktioniert es....

bei der neuen ReactUI will er anscheinend nicht Aktualiesieren...

**Comment by Schimi1983** [comment]
Also bei mir sind die fehler nur bei der ReactUI drin... bei der "alten Ansicht" ist alles in Ordnung

**Comment by unltdnetworx** [comment]
Jetzt sollte es auf Anhieb funktionieren.

**Comment by Schimi1983** [comment]
Jap... 

Keine Fehler im Log und keine "abgeschnittenen" namen... kann also von mir aus eine Stufe weiter ins "latest" :-)

**Comment by unltdnetworx** [comment]
Danke für die Rückmeldung
