### ISSUE TITLE
Changing values do not work

### ISSUE THREAD

**Issue by amiga4everyone** [unltdnetworx/ioBroker.stiebel-isg#49]
**Describe the bug**  
If I change the values ​​val82 and val83, this has no effect on the machine. The values ​​are read correctly, but changes are not written.

**To Reproduce**  
1. Change value val82 (fan level day) in the ioBroker from 2 to 0
2. Check changes in the web front end of the ISG - no change
3. After the pull interval, the value val82 is overwritten with the old value 2 again

**Expected behavior**  
I expect that value is written to the ISG

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.6.1
 - JS-Controller version: 3.2.16 
 - Node version: 12.22.1 
 - Operating system: Container on unraid 

**Additional context**  
For questions contact me at bernd@reichold.org

**Comment by unltdnetworx** [comment]
Okay, ich habe das Problem verstanden, nur leider kann ich es nicht reproduzieren.

Eine Aktualisierung des Wertes in den Objekten sollte nach einigen Sekunden eine Aktualisierung aller Werte aus dem Bereich "Einstellungen" zur Folge haben, spricht sie sollten kurz grün aufleuchten. Passiert das?

**Comment by amiga4everyone** [comment]
Schön, dass wir in Deutsch weiter schreiben können :-) Ich bin mir nicht ganz sicher, ob ich Dich jetzt richtig verstanden habe aber ich kann beschreiben was passiert. Leider weiß ich nicht, wie ich Dir hier Screenshots zukommen lassen kann. Kann ich auf dit github notification antworten und dort die Screenshots anhängen?  Bis dahin versuche ich es mal schriftlich.

Ich gehe im ioBroker unter Objekte nach stiebel-isg.0.Einstellungen.LÜFTEN.LÜFTUNGSSTUFEN.val82. Dort sehe ich den Wert, den ich auch im ISG sehe und den ich auch in der Anlage nachvollziehen kann. Jetzt klicke auf den Wert. Es öffnet sich der Dialog "Wert schreiben". Jetzt kommt es darauf an. Wenn ich den Wert unbestätigt setze erscheint dieser kurz grün, dann kurz rot und noch etwas später schwarz als Wert. Wenn ich ihn bestätigt setzte erscheint er kurz grün und dann schwarz. Aber egal welchen weg ich gehe, der Wert landet nicht in der Anlage. Im ISG bleibt die Lüfterstufe gleich. Um Sicherzustellen, dass es sich um den korrekten Wert handelt habe ich den Weg anders herum probiert und die Lüfterstufe über das ISG geändert und nach dem Intervall wird dieser Wert im ioBroker auch nagezeigt. Es wird also der Richtige wert abgefragt.

Wenn Du es genauer brauchst könnte ich Dir nur anbieten Dir Screenshots zukommen zu lassen oder eine Remotesession einzurichten.

CU
Bernd

**Comment by unltdnetworx** [comment]
Ich hab das Problem genau so verstanden. Mir stellt sich nur die Frage, warum das nicht in die Heizung geschrieben wird. Wenn ich einen der Werte ändere (ohne Bestätigungs-Häkchen) dann tritt genau das gleiche kurze Leuchten auf (grün, rot, schwarz). Das passt auch soweit. Aber kurz danach wird das Schreiben in die Heizung ausgeführt. Im Anschluss (nach wenigen Sekunden) sollten ALLE Punkte des Bereiches "Einstellungen" neu ausgelesen werden. Dadurch leuchten alle Werte kurz grün auf.

Aber das passiert offensichtlich nicht bei dir.

Evtl. installierst du dir den Adapter nochmal über die Github-Katze neu. Grundsätzlich sollte es funktionieren, habe es jetzt mehrfach getestet.

**Comment by unltdnetworx** [comment]
Alternativ kannst du dir auch mal meine Anleitung zur Anbindung mittels Modbus anschauen. Das geht wesentlich schneller und es entlastet das ISG, wenn die Seiten nicht mehr auslesen lassen musst, deren Werte du mit Modbus gewinnst. Leider kann Modbus nicht alle Werte auslesen, du brauchst also nach wie vor zusätzlich den Adapter. Allerdings kann man den Großteil der Seiten die ausgelesen werden dann aus dem ISG-Adapter entfernen.

[Anleitung](https://blog.unltd-networx.de/iobroker-stiebel-eltron-tecalor-waermepumpe-per-modbus-anbinden)

**Comment by amiga4everyone** [comment]
Vielen Dank schon mal für Deine Unterstützung. Ich werde beide Tipps die Tage mal ausprobieren und Dir auch Bescheid geben, egal was raus kommt.

 

CU

Bernd

 

 

Von: unltdnetworx ***@***.***> 
Gesendet: Dienstag, 22. Juni 2021 13:57
An: unltdnetworx/ioBroker.stiebel-isg ***@***.***>
Cc: amiga4everyone ***@***.***>; Author ***@***.***>
Betreff: Re: [unltdnetworx/ioBroker.stiebel-isg] Changing values do not work (#49)

 

Alternativ kannst du dir auch mal meine Anleitung zur Anbindung mittels Modbus anschauen. Das geht wesentlich schneller und es entlastet das ISG, wenn die Seiten nicht mehr auslesen lassen musst, deren Werte du mit Modbus gewinnst. Leider kann Modbus nicht alle Werte auslesen, du brauchst also nach wie vor zusätzlich den Adapter. Allerdings kann man den Großteil der Seiten die ausgelesen werden dann aus dem ISG-Adapter entfernen.

Anleitung <https://blog.unltd-networx.de/iobroker-stiebel-eltron-tecalor-waermepumpe-per-modbus-anbinden>

**Comment by amiga4everyone** [comment]
Hab's nicht ausgehalten und den Adapter direkt mal neu installiert und siehe da es funzt. Vielen Dank. Kaffee folgt

**Comment by unltdnetworx** [comment]
Sehr schön. Vielen Dank für die Rückmeldung und den Kaffee :)
Schau dir aber trotzdem mal Modbus an. Das ist echt eine große Entlassung für das Gerät.

**Comment by amiga4everyone** [comment]
Mach ich gerne. Aus Zeitgründen wird es aber bestimmt erst am Wochenende was.
