### ISSUE TITLE
1.7.1 auf 1.7.2 error im Log "UNCAUGHT_EXCEPTION"

### ISSUE THREAD

**Issue by Schimi1983** [unltdnetworx/ioBroker.stiebel-isg#51]
Nach dem Update von 1.7.1 auf 1.7.2

<html>
<body>

host.smarthome | 2021-07-28 16:36:51.383 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
stiebel-isg.0 | 2021-07-28 16:36:50.837 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 16:36:50.837 | error | Error: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-07-28 16:36:50.836 | error | uncaught exception: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
host.smarthome | 2021-07-28 16:36:10.970 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
stiebel-isg.0 | 2021-07-28 16:36:10.413 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 16:36:10.413 | error | Error: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-07-28 16:36:10.412 | error | uncaught exception: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
host.smarthome | 2021-07-28 16:35:39.627 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
stiebel-isg.0 | 2021-07-28 16:35:39.077 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 16:35:39.077 | error | Error: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-07-28 16:35:39.076 | error | uncaught exception: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
host.smarthome | 2021-07-28 16:35:08.278 | error | instance system.adapter.stiebel-isg.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
stiebel-isg.0 | 2021-07-28 16:35:07.719 | error | Exception-Code: MODULE_NOT_FOUND: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js
stiebel-isg.0 | 2021-07-28 16:35:07.718 | error | Error: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.stiebel-isg/main.js:59:25) at processImmediate (internal/timers.js:463:21)
stiebel-isg.0 | 2021-07-28 16:35:07.718 | error | uncaught exception: Cannot find module './src/i18n/de/translations.json'Require stack:- /opt/iobroker/node_modules/iobroker.stiebel-isg/main.js

</body>
</html>

**Comment by unltdnetworx** [comment]
Sry, about that. Please update over Github. Bug fixed

**Comment by unltdnetworx** [comment]
Pull request for stable version.
Should be online soon.

Please close this issue, if the bug is fixed.

**Comment by Schimi1983** [comment]
Fixed :-)
