### ISSUE TITLE
warnings 

### ISSUE THREAD

**Issue by amiga4everyone** [unltdnetworx/ioBroker.stiebel-isg#57]
I have a small problem with the ISG adapter. In the logs I regularly find warnings shown below. I use the adapter in version 1.7.3. The data for my system are: 

Node.js: 12.22.7
NPM: 6.14.15
Controller: 3.3.18

I think the problem is not serious but unsightly.

---log---
stiebel-isg.0 | 1331 | 2021-11-25 13:29:36.667 | warn | State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""
stiebel-isg.0 | 1331 | 2021-11-25 13:24:41.499 | warn | State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""
stiebel-isg.0 | 1331 | 2021-11-25 13:19:36.522 | warn | State value to set for "stiebel-isg.0.Start.val39" has value "11" greater than max ""

**Comment by unltdnetworx** [comment]
Please install the version via the github cat, delete the whole object tree of the adapter and restart the adapter.
Please respond, if the error is gone.

**Comment by amiga4everyone** [comment]
So, I have done everything as requested. The first 20 minutes look good. Normally the message would have appeared already. But I'll observe everything for another day and then get back to you. Thank you very much.

**Comment by amiga4everyone** [comment]
After another 20h of observation I can say that the error probably no longer occurs. Thank you

**Comment by unltdnetworx** [comment]
Fixed this long ago, but forgot to update the repo.
