### ISSUE TITLE
update to 1.3.2 is not working

### ISSUE THREAD

**Issue by FraatRamski** [unltdnetworx/ioBroker.stiebel-isg#6]
1. thanks for the plugin!!!
When I try to update i will get this error:

$ ./iobroker upgrade stiebel-isg
Update stiebel-isg from @1.2.4 to @1.3.2
NPM version: 6.4.1
npm install iobroker.stiebel-isg@1.3.2 --production --save --prefix "/opt/iobroker" (System call)
npm 
ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.stiebel-isg@1.3.2
npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/iobroker/.npm/_logs/2019-01-30T06_02_37_361Z-debug.log
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.stiebel-isg"
got /opt/iobroker/node_modules/iobroker.stiebel-isg/admin
upload [4] stiebel-isg.admin /opt/iobroker/node_modules/iobroker.stiebel-isg/admin/words.js words.js application/javascript
upload [3] stiebel-isg.admin /opt/iobroker/node_modules/iobroker.stiebel-isg/admin/stiebel-isg.png stiebel-isg.png image/png
upload [2] stiebel-isg.admin /opt/iobroker/node_modules/iobroker.stiebel-isg/admin/index_m.html index_m.html text/html
upload [1] stiebel-isg.admin /opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [0] stiebel-isg.admin /opt/iobroker/node_modules/iobroker.stiebel-isg/admin/i18n/de/translations.json i18n/de/translations.json application/json
Adapter "stiebel-isg" updated
process exited with code 0

**Comment by unltdnetworx** [comment]
Please try to update by Github (github-cat - symbol in iobroker). Maybe it hasn't been updated in the repository.

**Comment by FraatRamski** [comment]
Is working now, thanks again for the great plugin!
