### ISSUE TITLE
Warnungen aufgrund falscher Werte

### ISSUE THREAD

**Issue by danickel** [unltdnetworx/ioBroker.stiebel-isg#61]
Im Log habe ich regelmäßig Warnungen vom Adapter aufgrund von Werten außerhalb des gültigen Bereichs. 
Ich besitze eine LWZ504. Die Werte sollten eigentlich alle korrekt eingestellt und gültig sein. Die Werte wurden nicht über den Adapter gesetzt, sondern direkt an der Heizung oder per ISG Weboberfläche.

![grafik](https://user-images.githubusercontent.com/90868055/150569036-bb99518c-8b7e-4c1f-adf1-b56ac2dcb6be.png)

**Comment by unltdnetworx** [comment]
Bitte einmal den ganzen Objektbaum löschen und den Adapter neustarten. Das ist ein alter Fehler und seit einiger Zeit behoben. Leider werden die Datenpunkte nicht aktualisiert.
Die Datenpunkte werden wieder 1:1 erstellt, also kein Problem.

**Comment by danickel** [comment]
Ok, danke, dass hat schonmal etwas geholfen. 3 Warnungen sind verschwunden. Es bleibt aber noch folgende Warnung:

![grafik](https://user-images.githubusercontent.com/90868055/150687029-41dd87dd-61ab-44e6-8bca-fd956c896a88.png)

**Comment by unltdnetworx** [comment]
Das ist interessant. Kannst du mal bitte schauen, was die Weboberfläche zu den Min/Max-Werten sagt?

**Comment by danickel** [comment]
Ok, die Warnmeldung scheint berechtigt zu sein.
Ich nutze die Kühlfunktion nicht und habe auch noch nie etwas an den Standardwerten geändert:
![grafik](https://user-images.githubusercontent.com/90868055/150688013-97bb362a-9fb1-416c-aeca-d3d27d99b09c.png)

**Comment by unltdnetworx** [comment]
Sehr schön. Hätte mich jetzt gewundert, wie das ausgelöst wird.
Dann schließe ich diesen Issue.

**Comment by danickel** [comment]
Ja passt. Warnmeldung ist weg!
Danke für den schnellen Support!
