### ISSUE TITLE
how can I setup the lwz to produce warm water

### ISSUE THREAD

**Issue by radebold** [unltdnetworx/ioBroker.stiebel-isg#64]
I'm looking for information, how to setup my lwz to produce warm water.
Background is, if my batterie is full from solar i will push my lwz to take the free energy and start warm water.

I have tryed to set the status to warmwater, but I think it is only in combination with the scheduled hours possible.

What can I do ?

**Comment by unltdnetworx** [comment]
This is not an issue.
Please consider to ask in the iobroker forum.

But I've written a [blog-entry](https://blog.unltd-networx.de/iobroker-heizung-bei-pv-ueberschuss-aufheizen-version-20) for this target also.
