### ISSUE TITLE
Values of Boolean states are null but should be false

### ISSUE THREAD

**Issue by djanknecht** [unltdnetworx/ioBroker.stiebel-isg#66]
Hi. First of all thank you for the adapter!

My question: Why are the values of all boolean states (for example stiebel-isg.0.Info.ANLAGE.BETRIEBSSTATUS.HEIZEN or stiebel-isg.0.Info.ANLAGE.BETRIEBSSTATUS.WARMWASSERBETRIEB) "null" when they should be "false"? When accessing them via "getState", a warning is thrown: _getState "stiebel-isg.0.Info.ANLAGE.ENERGIEMANAGEMENT.Betriebszustand_3" not found (3)_ and the value is null. How can I workaround this problem?

Thanks and regards, 

Dirk
 
![grafik](https://user-images.githubusercontent.com/10382009/203643662-954ec288-ad7a-4ba5-a334-a811b5285999.png)

**Comment by unltdnetworx** [comment]
Bitte einmal den ganzen Objektbaum löschen, alternativ auch nur den einen Wert. Dieser wird dann neu erstellt und sollte passen. Falls nicht, kann ich mich voraussichtlich erst Ende Februar drum kümmern.
Alternativ einfach manuell den Typ des Werts ändern mittels des Schraubenschlüsselsymbols (Erweiterte Ansicht des Objektbaums aktivieren).

**Comment by djanknecht** [comment]
@unltdnetworx Danke! Habe heute auf Modbus umgestellt. Funktioniert einwandfrei!
