### ISSUE TITLE
Don't use (null) for States

### ISSUE THREAD

**Issue by tipp88** [unltdnetworx/ioBroker.stiebel-isg#67]
Bitte ändern dass boolean Werte kein Null bekommen. 
Speziell geht es mir um den Betriebsstatus (stiebel-isg.0.Info.STATUSANLAGE.BETRIEBSSTATUS) 
Hier werden die aktiven States mit dem Stati True versehen. Anstatt für die inaktiven Stati False zu verwenden, werden diese Null gesetzt. Das ist nicht schön, denn wenn ich diese Werte per Javascript trigger auswerte, wird immer eine Fehlermeldung generiert wenn der Wert Null ist, als wenn der State überhaupt nicht vorhanden ist. 
Für diese States sollte statt Null, einfach False verwendet werden. Das wäre super.

![image](https://user-images.githubusercontent.com/68737433/218442199-bb82bc50-5969-4bb0-994b-15c905d791c5.png)

![image](https://user-images.githubusercontent.com/68737433/218442089-a4c9e108-3407-42ec-aa82-a2f55cba245c.png)

**Comment by tipp88** [comment]
Der gleiche Fehler bei anderen Werten... es lässt sich keine vernünftige Steuerung bauen, weil der Adapter ständig Werte (null) setzt. Ich vermute wenn beim Aktualisieren ein Timeout oder ähnlich kommt. Einfach den vorherigen Wert lassen wäre hier schöner.
![image](https://user-images.githubusercontent.com/68737433/219036328-cb48dae1-e996-49ae-992b-cba3a33235dd.png)

**Comment by unltdnetworx** [comment]
Das Thema wurde schon mehrfach diskutiert, u.a. hier (#66 ) und im Forum. Aufgrund dessen. dass die ISG-Oberfläche Stati Betriebsstatuswerte nur anzeigt oder ausblendet, anstatt an und aus zu verwenden, lässt sich das nicht vernünftig lösen.
