### ISSUE TITLE
Außerplanmäßige Lüftung anstoßen

### ISSUE THREAD

**Issue by gimli1980** [unltdnetworx/ioBroker.stiebel-isg#68]
Hallo zusammen, 

gibt es eine Möglichkeit, über den Adapter die außerplanmäßige Lüftungszeit für die verschieden Lüftungsstufen anzustoßen?

Ich würde gerne täglich die Lüftung für 60 Minunten auf Stufe 3 stellen wenn wir aufgestanden sind damit das Schlafzimmer ordentlich durchgelüftet wird.

**Comment by unltdnetworx** [comment]
Das ist leider nicht möglich. Nur per manuellem Skript in ioBroker z.B.
Fragen dazu bitte im ioBroker Forum. Hier nur issues/Fehler melden.
